import { NavBar } from "@/components/layouts";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  // await checkBcApi();
  return (
    <html lang="en">
      <body
        className={`dark ${geistSans.variable} ${geistMono.variable} relative mb-5 antialiased`}
      >
        <Toaster />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
